### ISSUE TITLE
Rework keygen

### ISSUE THREAD

**Issue by dabasov** [0chain/keygen#4]
Keygen now uses a little bit out of sync key gen mechanism. To make it up to date we need to use key gen implemented in goSDK. 
- For herumi use generation with eth mnemonic and add appropriate run flag to sh script
eg.
```
//NewHerumiScheme - create a MiraclScheme object
func NewHerumiScheme() *HerumiScheme {
	return &HerumiScheme{
		id: BlsSignerInstance.NewID(),
	}
}

// GenerateKeys  generate fresh keys
func (b0 *HerumiScheme) GenerateKeys() (*Wallet, error) {
	return b0.generateKeys("0chain-client-split-key")
}

// GenerateKeysWithEth  generate fresh keys based on eth wallet
func (b0 *HerumiScheme) GenerateKeysWithEth(mnemonic, password string) (*Wallet, error) {
	if len(mnemonic) == 0 {
		return nil, fmt.Errorf("Mnemonic phase is mandatory.")
	}
	b0.Mnemonic = mnemonic

	_, err := bip39.NewSeedWithErrorChecking(b0.Mnemonic, password)
	if err != nil {
		return nil, fmt.Errorf("Wrong mnemonic phase.")
	}

	return b0.generateKeys(password)
}
```
- for ed25519 use goSDK implementation also
- rework Docker to build container from similar to how it is build for blobber-stake (with go mod and standalone build)
- add key serialization to file in the format it was used before for backward compatibility

**Comment by peterlimg** [comment]
Closed by #5
